### ISSUE TITLE
unable to get dbsync to query

### ISSUE THREAD

**Issue by ub5znq8n** [bitfinexcom/bfx-report-electron#65]
I am unable to get the db sync portion of the software to function.  Operating on Linux Mint.

I am not getting any error messages, but it never succeeds and ends up switching to Query Offline mode.

I am able to generate basic ledger reports / wallet reports, but am hoping to be able to get some more data via the Tax Report function, which I cant unless db sync works.

Thanks in advance

**Comment by ezewer** [comment]
@ub5znq8n  actually we are going to change the DB from SQLITE3 to Better-Sqlite tomorrow and implement some new optimizations. Lets check after this and if still not working we can check whats the issue.

**Comment by ezewer** [comment]
@ub5znq8n just sent the new version to electron, however was not able to create the releases as its failing the signature keys for a dependency. 
Can check creating the releases or wait some days while the signature is fixed.
Would keep you updated.

**Comment by ub5znq8n** [comment]
Thanks for the update! Ill keep waiting patiently hopeful.  I appreciate the help.

**Comment by ezewer** [comment]
@ub5znq8n just uploaded the version 3.2.0 when possible can confirm if this works please?

**Comment by ub5znq8n** [comment]
> @ub5znq8n just uploaded the version 3.2.0 when possible can confirm if this works please?

Sorry for the delayed reply.

@ezewer I just attempted the compiled build in linux but the db sync doesnt complete.  In this build I still dont get an error and it just switches to offline sync.  I also do not see any log file to see if there is anything going on in the background.  Am I potentially missing a dependency?

If I build via npm install, the build works, but upon running the electron I get an error regarding missing file `triggerElectronLoad.js`:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/user/git/bfx-report-electron/bfx-report-ui/build/triggerElectronLoad.js'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.<anonymous> (/home/user/git/bfx-report-electron/src/trigger-electron-load.js:11:35)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Function.Module._load (electron/js2c/asar.js:748:26)
```

**Comment by ezewer** [comment]
@ub5znq8n 

>  build in linux but the db sync doesnt complete. In this build I still dont get an error and it just switches to offline sync
If its stop the sync and goes to offline mode means that is completed, why do you think if not completed, is there some information missing?

> If I build via npm install, the build works, but upon running the electron I get an error regarding missing file
Try removing the node_modules folder and deleting the package-lock.json file if there is one 
Sample code:
```
rm -r node_modules
rm package-lock.json
```
Does this work?

**Comment by jcbit** [comment]
I am having the same issue. I am running the latest compiled version on WIndows

**Comment by ezewer** [comment]
@jcbit would be pushing an update at the end of the week that would improve the sync. 
By the way if leave the program opened, it never ends up syncing?

**Comment by jcbit** [comment]
No, I've left it open for days. It starts syncing and then it just goes to Query Offline (like if it had finished syncing) but it didn't sync anything.

**Comment by ezewer** [comment]
Mhmm strange, lets check if this new update fixes the issue, if not would ask more details and check this cases. 
Would write when release is live.

**Comment by ezewer** [comment]
@ub5znq8n , @jcbit can ask you if you could send me the error logs from your accounts as to find the issues please? 
Can send to ezequiel.wernicke@bitfinex.com

*Logs can be find in:*
```console
Windows: C:\Users\username\AppData\Roaming\bfx-report-electron\logs
IOS: ~/Library/Application Support/bfx-report-electron/logs
Linux: ~/.config/bfx-report-electron/logs
```

**Comment by jcbit** [comment]
Sure thing, sending it in a few minutes

**Comment by jcbit** [comment]
Hi! Any updates on this?

**Comment by ezewer** [comment]
Hi @jcbit i replied the email 8 days ago, copying the answer here also: 

From the logs shared i see that the errors are related to Gateway Timeout (504)
This might be related to the firewall configuration of windows or other your router, being this last more unlikely. 
Can you please check the following please? 

- Fix faulty firewall configurations.
- Look for server connectivity issues.

Leave you a link to an instruction on how to do this for windows: https://www.dummies.com/computers/operating-systems/windows-10/how-to-change-windows-10-firewall-settings-to-allow-certain-programs/#:~:text=Make%20sure%20that%20the%20program,an%20App%20through%20Windows%20Firewall. 
If uninstalling the software and installing it again i think it should ask to reset the permissions, however the link should work fine without uninstalling. 
Please let me know how it goes.

**Comment by jcbit** [comment]
The executable was already added as an exception to the three network profiles and I even went ahead and disabled firewall totally.  I can connect to Bitfinex via web browser and with Query Online on the reporting app, any idea of what connectivity tests I could perform? I am going to try to install it on a Mac laptop I have tomorrow and see if that makes any difference.

**Comment by ezewer** [comment]
With this new configuration, do you still have the Gateway Timeout (504) on the logs? 
I think that the logs are the best way as to check connectivity. 
Please let me know how it goes.

**Comment by jcbit** [comment]
Yes, and still getting the same error in the logs. Also, tried it on my mac and getting the same error.

**Comment by ezewer** [comment]
@jcbit can you try using your phone as a hotspot, might be related to a network firewall configuration.

**Comment by jcbit** [comment]
Just tried from my laptop (mac) on a coffee shop and then used my hotspot (with and without Cloudflare WARP) and same thing on the three scenarios :(

**Comment by ezewer** [comment]
Getting same logs Gateway Timeout (504) ? Or do you get other logs?

**Comment by jcbit** [comment]
Sorry, thought I had replied. Yes, still Gateway timeout 504

**Comment by ezewer** [comment]
@jcbit this is really strange, can you try with another api keys just in case?

**Comment by jcbit** [comment]
Hi, tried to create a new API key and installed it in another computer and still no dice. I also verified and it has all the read only permissions set up. 

I do a ping to api-pub.bitfinex.com and it resolves to 104.16.175.181, not sure if this issue is because of cloudflare or something and things timing out with the gateway based on the error message. Clearly the app is able to communicate with something but it is timing out.

**Comment by ezewer** [comment]
Hi @jcbit can we close this one? If not can re open using the error log from the software? would give us more perspective as to debug.
